### ISSUE TITLE
SDK install doesn't work.

### ISSUE THREAD

**Issue by dbalan** [Sorixelle/pebble.nix#1]
# Problem
SDK install fails because virtualenv is somehow broken

# Ways to reproduce
1. Get nix shell with pebble.nix
```nix
(import
  (builtins.fetchTarball https://github.com/Sorixelle/pebble.nix/archive/master.tar.gz)
).pebbleEnv { }
```
2. Execute
```
pebble sdk install 4.2
```
I am wondering if it has something do with python2.7 deprecation, or am I doing something wrong.

# Logs
```
[nix-shell:~/code/public/cards-example]$ pebble sdk install 4.3
/nix/store/y1pnzm0nkyv23iwrarzh8ifr2nd7r45k-python2.7-oauth2client-4.1.3/lib/python2.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/dj/.pebble-sdk/oauth/oauth_storage: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Installing SDK...
To use the Pebble SDK, you must agree to the following:

PEBBLE TERMS OF USE
https://developer.rebble.io/developer.getpebble.com/legal/terms-of-use/index.html

PEBBLE DEVELOPER LICENSE
https://developer.rebble.io/developer.getpebble.com/legal/sdk-license/index.html

Do you accept the Pebble Terms of Use and the Pebble Developer License? (y/n) y
Downloading...
100%[=====================================================================================================]   8.71 MB/s 0:00:00
Extracting...
Preparing virtualenv... (this may take a while)
Traceback (most recent call last):
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/bin/.virtualenv-wrapped", line 6, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/lib/python2.7/site-packages/virtualenv/run/__init__.py", line 5, in <module>
    from ..app_data import AppDataAction, AppDataDisabled, TempAppData
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/lib/python2.7/site-packages/virtualenv/app_data/__init__.py", line 13, in <module>
    from .via_disk_folder import AppDataDiskFolder
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/lib/python2.7/site-packages/virtualenv/app_data/via_disk_folder.py", line 35, in <module>
    from virtualenv.util.lock import ReentrantFileLock
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/lib/python2.7/site-packages/virtualenv/util/lock.py", line 11, in <module>
    from virtualenv.util.path import Path
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/lib/python2.7/site-packages/virtualenv/util/path/__init__.py", line 3, in <module>
    from ._pathlib import Path
  File "/nix/store/l9sh2gmzh0z1ykkafb81szdxiir1jk1q-python2.7-virtualenv-20.0.28/lib/python2.7/site-packages/virtualenv/util/path/_pathlib/__init__.py", line 42, in <module>
    from pathlib2 import Path
  File "/nix/store/g37pw39qxqpwlkrdys3j1dj0ssyh218a-python2.7-pathlib2-2.3.5/lib/python2.7/site-packages/pathlib2/__init__.py", line 52, in <module>
    from scandir import scandir as os_scandir
  File "/nix/store/kwrsdgrr4abn4z1f4kz02zbhbirryhvh-python2.7-scandir-1.10.0/lib/python2.7/site-packages/scandir.py", line 452, in <module>
    libc = ctypes.CDLL(ctypes.util.find_library('c'), use_errno=True)
  File "/nix/store/6xyf4rb6ch0xgf6c7x2p0g6l6k76yqn2-python-2.7.18/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: 0x0000000000005f61: cannot open shared object file: No such file or directory
Failed.
Cleaning up failed install...
Done.
Traceback (most recent call last):
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/bin/.pebble-wrapped", line 9, in <module>
    sys.exit(run_tool())
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/lib/python2.7/site-packages/pebble_tool/__init__.py", line 44, in run_tool
    args.func(args)
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/lib/python2.7/site-packages/pebble_tool/commands/base.py", line 47, in <lambda>
    parser.set_defaults(func=lambda x: cls()(x))
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/lib/python2.7/site-packages/pebble_tool/commands/sdk/manage.py", line 23, in __call__
    args.sub_func(args)
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/lib/python2.7/site-packages/pebble_tool/commands/sdk/manage.py", line 108, in do_install
    sdk_manager.install_remote_sdk(args.version)
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/lib/python2.7/site-packages/pebble_tool/sdk/manager.py", line 153, in install_remote_sdk
    self.install_from_url(sdk_info['url'])
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/lib/python2.7/site-packages/pebble_tool/sdk/manager.py", line 90, in install_from_url
    self._install_from_handle(f)
  File "/nix/store/34k9z4lrvhwyhng80qzahyplakx9y5ar-python2.7-pebble-tool-4.6rc1/lib/python2.7/site-packages/pebble_tool/sdk/manager.py", line 117, in _install_from_handle
    subprocess.check_call(["virtualenv", virtualenv_path])
  File "/nix/store/6xyf4rb6ch0xgf6c7x2p0g6l6k76yqn2-python-2.7.18/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', u'/home/dj/.pebble-sdk/SDKs/4.3/.env']' returned non-zero exit status 1
````

**Comment by Sorixelle** [comment]
That is a very strange error - what OS and what version are you using? I'll have to see if I can reproduce this myself.

**Comment by dbalan** [comment]
I am on nixos
```
 nix-info                                                                                                                                                                                                                                                                                                            !10001
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.10, channels(root): "nixos-20.09.3160.5c53c720ff6, unstable-21.03pre267696.fab6fcdceb2", channels(dj): "home-manager-20.09", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by Sorixelle** [comment]
Even more bizarre, since I'm on NixOS as well, albeit tracking nixpkgs unstable instead of 20.09:
```
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.4pre20210317_8a5203d, channels(ruby): "", channels(root): "home-manager, nixos-21.03pre260232.733e537a8ad", nixpkgs: /etc/nixpkgs
```
If you delete the `shell.nix`, run a `sudo nix-collect-garbage`, and recreate it, that should redownload all the derivations. Maybe that will sort it out? If not, I'll see if I can spin up a similar NixOS install.

**Comment by dbalan** [comment]
The error was happening due my external python paths (I am not 100% sure the exact reason) but using `nix-shell --pure` solves the problem. I can install the sdk, but build still fails :( I am using https://github.com/pebble-examples/cards-example as a test code.

Maybe this is related, but I think original problem is solved, so feel free to close the Issue if you'd like.

```
pebble clean
/nix/store/y1pnzm0nkyv23iwrarzh8ifr2nd7r45k-python2.7-oauth2client-4.1.3/lib/python2.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/dj/.pebble-sdk/oauth/oauth_storage: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
'distclean' finished successfully (0.002s)

[nix-shell:~/code/public/cards-example]$ pebble build
/nix/store/y1pnzm0nkyv23iwrarzh8ifr2nd7r45k-python2.7-oauth2client-4.1.3/lib/python2.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/dj/.pebble-sdk/oauth/oauth_storage: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Setting top to                           : /home/dj/code/public/cards-example
Setting out to                           : /home/dj/code/public/cards-example/build
Checking for program webpack             : /home/dj/.pebble-sdk/SDKs/current/node_modules/.bin/webpack
WARNING: enableMultiJS is not enabled for this project. message_keys.json will not be included in your project unless you add it to your pebble-js-app.js file.
Found Pebble SDK for basalt in:          : /home/dj/.pebble-sdk/SDKs/current/sdk-core/pebble/basalt
Checking for program gcc,cc              : arm-none-eabi-gcc
Checking for program ar                  : arm-none-eabi-ar
Found Pebble SDK for aplite in:          : /home/dj/.pebble-sdk/SDKs/current/sdk-core/pebble/aplite
Checking for program gcc,cc              : arm-none-eabi-gcc
Checking for program ar                  : arm-none-eabi-ar
'configure' finished successfully (0.050s)
Waf: Entering directory `/home/dj/code/public/cards-example/build'
[ 3/56] message_key_definitions:  -> build/src/message_keys.auto.c
[ 3/56] message_key_header:  -> build/include/message_keys.auto.h
[ 3/56] message_key_json:  -> build/js/message_keys.json
[ 7/56] basalt | subst: ../../../.pebble-sdk/SDKs/current/sdk-core/pebble/common/pebble_app.ld.template -> build/basalt/pebble_app.ld.auto
[ 7/56] basalt | appinfo.auto.c:  -> build/basalt/appinfo.auto.c
[ 6/56] basalt | appinfo.json:  -> build/appinfo.json
[ 7/56] basalt | reso: resources/Pebble_50x50_Generic_weather.pdc -> build/basalt/resources/Pebble_50x50_Generic_weather.pdc.ICON_GENERIC_WEATHER.reso
[ 8/56] basalt | reso: resources/Pebble_50x50_Heavy_rain.pdc -> build/basalt/resources/Pebble_50x50_Heavy_rain.pdc.ICON_HEAVY_RAIN.reso
[10/56] basalt | reso: resources/Pebble_50x50_Heavy_snow.pdc -> build/basalt/resources/Pebble_50x50_Heavy_snow.pdc.ICON_HEAVY_SNOW.reso
[10/56] basalt | reso: resources/Pebble_50x50_Light_rain.pdc -> build/basalt/resources/Pebble_50x50_Light_rain.pdc.ICON_LIGHT_RAIN.reso
[11/56] basalt | reso: resources/Pebble_50x50_Light_snow.pdc -> build/basalt/resources/Pebble_50x50_Light_snow.pdc.ICON_LIGHT_SNOW.reso
[12/56] basalt | reso: resources/Pebble_50x50_Partly_cloudy.pdc -> build/basalt/resources/Pebble_50x50_Partly_cloudy.pdc.ICON_PARTLY_CLOUDY.reso
[13/56] basalt | reso: resources/Pebble_50x50_Sunny_day.pdc -> build/basalt/resources/Pebble_50x50_Sunny_day.pdc.ICON_SUNNY_DAY.reso
[14/56] basalt | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.16.o
[15/56] basalt | resource_ball: build/basalt/resources/Pebble_50x50_Generic_weather.pdc.ICON_GENERIC_WEATHER.reso build/basalt/resources/Pebble_50x50_Heavy_rain.pdc.ICON_HEAVY_RAIN.reso build/basalt/resources/Pebble_50x50_Heavy_snow.pdc.ICON_HEAVY_SNOW.reso build/basalt/resources/Pebble_50x50_Light_rain.pdc.ICON_LIGHT_RAIN.reso build/basalt/resources/Pebble_50x50_Light_snow.pdc.ICON_LIGHT_SNOW.reso build/basalt/resources/Pebble_50x50_Partly_cloudy.pdc.ICON_PARTLY_CLOUDY.reso build/basalt/resources/Pebble_50x50_Sunny_day.pdc.ICON_SUNNY_DAY.reso -> build/basalt/system_resources.resball
[18/56] basalt | generate_resource_id_header: build/basalt/system_resources.resball -> build/basalt/src/resource_ids.auto.h
[18/56] basalt | generate_resource_id_definitions: build/basalt/system_resources.resball -> build/basalt/src/resource_ids.auto.c
[18/56] basalt | generate_pbpack: build/basalt/system_resources.resball -> build/basalt/app_resources.pbpack
[19/56] basalt | c: build/basalt/src/resource_ids.auto.c -> build/basalt/src/resource_ids.auto.c.16.o
[20/56] basalt | c: src/weather_app_resources.c -> build/src/weather_app_resources.c.16.o
[21/56] basalt | c: build/basalt/appinfo.auto.c -> build/basalt/appinfo.auto.c.16.o
[22/56] basalt | c: src/gdraw_command_transforms.c -> build/src/gdraw_command_transforms.c.16.o
[23/56] basalt | c: src/weather_app.c -> build/src/weather_app.c.16.o
[24/56] basalt | c: src/weather_app_data.c -> build/src/weather_app_data.c.16.o
[25/56] basalt | c: src/weather_app_animations.c -> build/src/weather_app_animations.c.16.o
../src/weather_app_animations.c: In function 'property_animation_update_animated_numbers':
../src/weather_app_animations.c:39:45: error: cast between incompatible function types from 'GRectSetter' {aka 'void (*)(void *, struct GRect)'} to 'void (*)(WeatherAppData *, WeatherDataViewNumbers)' {aka 'void (*)(struct <anonymous> *, struct <anonymous>)'} [-Werror=cast-function-type]
   WeatherDataAnimatedNumbersSetter setter = (WeatherDataAnimatedNumbersSetter)impl->accessors.setter.grect;
                                             ^
../src/weather_app_animations.c: At top level:
../src/weather_app_animations.c:52:26: error: cast between incompatible function types from 'void (*)(WeatherAppMainWindowViewModel *, WeatherDataViewNumbers)' {aka 'void (*)(struct <anonymous> *, struct <anonymous>)'} to 'void (*)(void *, GRect)' {aka 'void (*)(void *, struct GRect)'} [-Werror=cast-function-type]
     .setter = { .grect = (const GRectSetter) set_animated_numbers, },
                          ^
../src/weather_app_animations.c:53:26: error: cast between incompatible function types from 'WeatherDataViewNumbers (*)(WeatherAppMainWindowViewModel *)' {aka 'struct <anonymous> (*)(struct <anonymous> *)'} to 'GRectReturn (*)(void *)' {aka 'struct GRect (*)(void *)'} [-Werror=cast-function-type]
     .getter = { .grect = (const GRectGetter) get_animated_numbers, },
                          ^
cc1: all warnings being treated as errors
../src/weather_app_data.c: In function 'weather_app_view_model_set_highlow':
../src/weather_app_data.c:18:75: error: '%d' directive output may be truncated writing between 1 and 6 bytes into a region of size between 4 and 9 [-Werror=format-truncation=]
   snprintf(model->highlow.text, sizeof(model->highlow.text), "HI %d°, LO %d°", model->highlow.high, model->highlow.low);
                                                                           ^~
../src/weather_app_data.c:18:62: note: directive argument in the range [-32768, 32767]
   snprintf(model->highlow.text, sizeof(model->highlow.text), "HI %d°, LO %d°", model->highlow.high, model->highlow.low);
                                                              ^~~~~~~~~~~~~~~~~~
../src/weather_app_data.c:18:3: note: 'snprintf' output between 15 and 25 bytes into a destination of size 20
   snprintf(model->highlow.text, sizeof(model->highlow.text), "HI %d°, LO %d°", model->highlow.high, model->highlow.low);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/weather_app_data.c: In function 'weather_app_view_model_set_temperature':
../src/weather_app_data.c:23:75: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
   snprintf(model->temperature.text, sizeof(model->temperature.text), "%d°", model->temperature.value);
                                                                           ^
../src/weather_app_data.c:23:3: note: 'snprintf' output between 4 and 9 bytes into a destination of size 8
   snprintf(model->temperature.text, sizeof(model->temperature.text), "%d°", model->temperature.value);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/weather_app_data.c: In function 'weather_app_view_model_fill_strings_and_pagination':
../src/weather_app_data.c:48:84: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
   snprintf(view_model->pagination.text, sizeof(view_model->pagination.text), "%d/%d", view_model->pagination.idx, view_model->pagination.num);
                                                                                    ^
../src/weather_app_data.c:48:3: note: 'snprintf' output between 4 and 9 bytes into a destination of size 8
   snprintf(view_model->pagination.text, sizeof(view_model->pagination.text), "%d/%d", view_model->pagination.idx, view_model->pagination.num);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Waf: Leaving directory `/home/dj/code/public/cards-example/build'
Build failed
 -> task in 'basalt/pebble-app.elf' failed (exit status 1):
	{task 139831175399504: c weather_app_animations.c -> weather_app_animations.c.16.o}
['arm-none-eabi-gcc', '-std=c99', '-mcpu=cortex-m3', '-mthumb', '-ffunction-sections', '-fdata-sections', '-g', '-fPIE', '-Os', '-D_TIME_H_', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-error=unused-function', '-Wno-error=unused-variable', '-I/home/dj/.pebble-sdk/SDKs/current/sdk-core/pebble/basalt/include', '-I/home/dj/code/public/cards-example/build', '-I/home/dj/code/public/cards-example', '-I/home/dj/code/public/cards-example/build/include', '-I/home/dj/code/public/cards-example/include', '-I/home/dj/code/public/cards-example/build/src', '-I/home/dj/code/public/cards-example/src', '-I/home/dj/code/public/cards-example/build/basalt', '-I/home/dj/code/public/cards-example/basalt', '-DRELEASE', '-DPBL_PLATFORM_BASALT', '-DPBL_COLOR', '-DPBL_RECT', '-DPBL_MICROPHONE', '-DPBL_SMARTSTRAP', '-DPBL_HEALTH', '-DPBL_COMPASS', '-DPBL_SMARTSTRAP_POWER', '-DPBL_DISPLAY_WIDTH=144', '-DPBL_DISPLAY_HEIGHT=168', '-DPBL_SDK_3', '-D__FILE_NAME__="weather_app_animations.c"', '../src/weather_app_animations.c', '-c', '-o', 'src/weather_app_animations.c.16.o']
 -> task in 'basalt/pebble-app.elf' failed (exit status 1):
	{task 139831175399696: c weather_app_data.c -> weather_app_data.c.16.o}
['arm-none-eabi-gcc', '-std=c99', '-mcpu=cortex-m3', '-mthumb', '-ffunction-sections', '-fdata-sections', '-g', '-fPIE', '-Os', '-D_TIME_H_', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-error=unused-function', '-Wno-error=unused-variable', '-I/home/dj/.pebble-sdk/SDKs/current/sdk-core/pebble/basalt/include', '-I/home/dj/code/public/cards-example/build', '-I/home/dj/code/public/cards-example', '-I/home/dj/code/public/cards-example/build/include', '-I/home/dj/code/public/cards-example/include', '-I/home/dj/code/public/cards-example/build/src', '-I/home/dj/code/public/cards-example/src', '-I/home/dj/code/public/cards-example/build/basalt', '-I/home/dj/code/public/cards-example/basalt', '-DRELEASE', '-DPBL_PLATFORM_BASALT', '-DPBL_COLOR', '-DPBL_RECT', '-DPBL_MICROPHONE', '-DPBL_SMARTSTRAP', '-DPBL_HEALTH', '-DPBL_COMPASS', '-DPBL_SMARTSTRAP_POWER', '-DPBL_DISPLAY_WIDTH=144', '-DPBL_DISPLAY_HEIGHT=168', '-DPBL_SDK_3', '-D__FILE_NAME__="weather_app_data.c"', '../src/weather_app_data.c', '-c', '-o', 'src/weather_app_data.c.16.o']
Build failed.
```

**Comment by Sorixelle** [comment]
Huh, strange. Might add that flag to the README information in case anyone else runs across a similar issue. The error you're getting there definitely looks more like a bug in the code you're building, so I think we can call this one closed since it's working now.

**Comment by dbalan** [comment]
Thanks for the help!
